---
title: "Day 3"
output: html_document
date: "2024-11-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(sf)
library(ggplot2)
library(dplyr)
library(ggtext)
```

```{r, include =FALSE}
recreational_spaces <- st_read("C:/Users/raymo/Documents/Fall 2024/MUSA6310 Communication/30 Days Mapping Challenge/Day 3 Polygon/Living_Near_Recreational_Space_-115450154399010474.geojson")
```

```{r}
recreational_spaces_filtered <- recreational_spaces %>%
  filter(!Geo_Name %in% c("Unincorporated - San Clemente Island", 
                          "Unincorporated - Santa Catalina Island", 
                          "City of Avalon"))
```

```{r}
ggplot() +
  geom_sf(data = recreational_spaces_filtered, aes(fill = W_rec_space), color = "NA") +
  scale_fill_gradient(low = "lightgreen", high = "darkgreen", name = "Population%", 
                      na.value = "gray95") +
  theme_minimal() +
  labs(title = "<span style='color:darkgreen;'>Green Space</span> Accessibility Map, Los Angeles",
       subtitle = "Percentage of Population Within 10-Minute Walk of Recreational Spaces",
       caption = "30 Day Map Challenge 2024 | Day 3 - Polygon \nAuthor: Ray Ma \nSource: LA County Department of Public Health",) +
  theme(legend.position = "right",
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        plot.caption = element_text(hjust = 0, size = 10),
        plot.title = ggtext::element_markdown(size = 14, face = "bold")
)
```