---
title: "Day 2"
output: html_document
date: "2024-11-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,message=FALSE, warning=FALSE, cache=FALSE, include= FALSE}

library(httr)
library(sf)
library(ggplot2)
library(ggspatial)
library(prettymapr)

api_url <- "https://services.arcgis.com/RmCCgQtiZLDCtblq/arcgis/rest/services/MTA_Metro_Lines/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson"
```

```{r, include=FALSE}
response <- GET(api_url)
metro_data <- content(response, "text")
metro_lines <- st_read(metro_data)
```

```{r, message=FALSE, warning=FALSE}
# Define a named vector for the colors
line_colors <- c(
  "Metro A Line (Blue)" = "blue",
  "Metro B Line (Red)" = "red",
  "Metro C Line (Green)" = "green",
  "Metro D Line (Purple)" = "purple",
  "Metro E Line (Expo)" = "gold",
  "Metro G Line (Orange)" = "orange",
  "Metro J Line (Silver)" = "gray",
  "Metro K Line" = "pink",
  "Metro L Line (Gold)" = "blue",
  "Regional Connector" = "black"
)

ggplot() +
  annotation_map_tile("cartolight", zoom = 10) +
  geom_sf(data = metro_lines, aes(color = LABEL), size = 1) +
  labs(
    title = "MTA Metro Rail Lines, Los Angeles 2023",
    caption = "30 Day Map Challenge 2024 | Day 2 - Line \nAuthor: Ray Ma \nSource: MTA, LA Metro, LA County",
    color = "Metro Lines"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold", margin = margin(b = 10)),
    legend.position = c(0.85, 0.3),
    legend.background = element_rect(fill = "white", color = "black"),
    legend.key.size = unit(0.4, "cm"),
    legend.text = element_text(size = 7),
    legend.title = element_text(size = 9),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.caption = element_text(hjust = 0, size = 10)
  )


```
